version: '3.8'

services:
  api:
    build: .
    container_name: wealtharena-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount environment file
      - ./.env:/app/.env:ro
      # Persist data and models
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
