# WealthArena Trading System Configuration

# Data Configuration
data:
  start_date: "2020-01-01"
  end_date: "2024-01-01"
  asx_symbols:
    stocks: 200  # Top 200 ASX stocks
    etfs: 50     # Major ETFs
    reits: 30    # REITs
    currencies: 10  # Major currency pairs
    crypto: 10   # Major cryptocurrencies

# Training Configuration
training:
  lookback_window: 5
  prediction_horizon: 1
  validation_split: 0.2
  test_split: 0.2
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  early_stopping_patience: 10
  
  # Model-specific configurations
  models:
    stocks:
      model_type: "xgboost"
      features: ["Open", "High", "Low", "Close", "Volume", "SMA_20", "RSI", "MACD"]
      lookback_window: 5
    crypto:
      model_type: "lightgbm"
      features: ["Open", "High", "Low", "Close", "Volume", "SMA_20", "RSI", "MACD", "ATR"]
      lookback_window: 7
    etf:
      model_type: "random_forest"
      features: ["Open", "High", "Low", "Close", "Volume", "SMA_20", "RSI", "MACD", "BB_upper", "BB_lower"]
      lookback_window: 3
    currencies:
      model_type: "svr"
      features: ["Open", "High", "Low", "Close", "Volume", "SMA_20", "RSI", "MACD", "ATR", "ADX"]
      lookback_window: 10
    reits:
      model_type: "gradient_boosting"
      features: ["Open", "High", "Low", "Close", "Volume", "SMA_20", "RSI", "MACD", "OBV", "MFI"]
      lookback_window: 5

# Meta Agent Configuration
meta_agent:
  fusion_method: "weighted"  # voting, stacking, weighted, neural
  model_weights:
    stocks: 0.3
    crypto: 0.2
    etf: 0.2
    currencies: 0.2
    reits: 0.1
  confidence_threshold: 0.3
  risk_tolerance: 0.1
  max_position_size: 0.2
  rebalance_frequency: 7  # days

# Metrics Configuration
metrics:
  collection_interval: 60  # seconds
  retention_days: 30
  
  # Backend API Metrics
  backend_api:
    response_time_threshold: 1.0  # seconds
    error_rate_threshold: 0.05    # 5%
    cpu_threshold: 80             # 80%
    memory_threshold: 85          # 85%
  
  # Pipeline Metrics
  pipeline:
    success_rate_threshold: 0.95  # 95%
    failure_rate_threshold: 0.05  # 5%
    duration_threshold: 60        # seconds
  
  # Code Quality Metrics
  code_quality:
    cyclomatic_complexity_threshold: 10
    duplication_rate_threshold: 0.05  # 5%
    test_coverage_threshold: 0.8      # 80%
    technical_debt_threshold: 50      # hours
  
  # Data Store Metrics
  data_store:
    query_latency_threshold: 0.1      # seconds
    p95_latency_threshold: 0.2        # seconds
    p99_latency_threshold: 0.5        # seconds
    disk_usage_threshold: 90          # 90%
  
  # Scraping Metrics
  scraping:
    success_rate_threshold: 0.9       # 90%
    throughput_threshold: 100         # pages/hour
    response_time_threshold: 2.0      # seconds
  
  # ML Metrics
  ml:
    inference_time_threshold: 0.01    # seconds
    rmse_threshold: 0.1
    auc_threshold: 0.8
    f1_score_threshold: 0.8
  
  # Testing Metrics
  testing:
    coverage_threshold: 0.8           # 80%
    failure_rate_threshold: 0.05      # 5%

# Reporting Configuration
reporting:
  weekly_reports: true
  email_notifications: false
  output_formats: ["json", "html", "pdf"]
  
  # Email Configuration (if enabled)
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "your_email@gmail.com"
    password: "your_password"
    from_email: "your_email@gmail.com"
    recipients: ["admin@wealtharena.com"]
  
  # Report Content
  content:
    include_charts: true
    include_recommendations: true
    include_alerts: true
    include_trends: true

# Paths Configuration
paths:
  data_dir: "data"
  models_dir: "models"
  metrics_dir: "metrics"
  reports_dir: "reports"
  logs_dir: "logs"
  config_dir: "config"

# System Configuration
system:
  timezone: "UTC"
  log_level: "INFO"
  max_workers: 4
  memory_limit: "8GB"
  
  # Trading Configuration
  trading:
    daily_timeframe: true
    trading_hours: "09:00-16:00"  # UTC
    max_positions: 10
    position_size_limit: 0.2      # 20% of portfolio
    stop_loss: 0.08               # 8%
    take_profit: 0.20             # 20%
  
  # Risk Management
  risk_management:
    max_drawdown: 0.15            # 15%
    max_correlation: 0.7          # 70%
    var_confidence: 0.95          # 95%
    var_limit: 0.05               # 5% daily loss limit

# Performance Configuration
performance:
  target_annual_return: 0.25      # 25%
  target_sharpe_ratio: 2.0
  target_max_drawdown: 0.15       # 15%
  target_win_rate: 0.6            # 60%
  
  # Benchmarking
  benchmarks:
    - "SPY"  # S&P 500
    - "QQQ"  # NASDAQ
    - "IWM"  # Russell 2000
    - "EFA"  # EAFE
    - "VTI"  # Total Stock Market

# Monitoring Configuration
monitoring:
  health_check_interval: 300      # 5 minutes
  alert_cooldown: 3600           # 1 hour
  max_alerts_per_hour: 10
  
  # Alert Channels
  alerts:
    email: true
    slack: false
    webhook: false
  
  # Slack Configuration (if enabled)
  slack:
    webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
    channel: "#trading-alerts"
    username: "WealthArena Bot"

# Development Configuration
development:
  debug_mode: false
  test_mode: false
  mock_data: false
  verbose_logging: false
  
  # Testing
  testing:
    quick_test_duration: 300      # 5 minutes
    test_data_size: 1000          # records
    test_symbols: 10
    test_epochs: 5